### ISSUE TITLE
readme requires correction of plugin download URL

### ISSUE THREAD

**Issue by dguduguntla** [oliver/gedit-file-search#15]
When I tried to follow the instructions on ReadMe file on my 12.04 LTS Ubuntu, the plugin is not loaded.  Because under [1], the plugin URL points to 0.5 version.  After using the 1.0 URL, the plugin activation worked. You may want to correct that file to use the download URL: https://github.com/oliver/gedit-file-search/releases/download/GEDIT_FILE_SEARCH_V1.0/gedit-file-search-1.0.tgz

**Comment by oliver** [comment]
Thanks for spotting this; should be fixed now!
