### ISSUE TITLE
Can't build/show window... please, help!

### ISSUE THREAD

**Issue by careca1970** [oliver/gedit-file-search#16]
On gedit - Version 3.8.3 | Python 3.3.2 | gnome 3.8.4 | Fedora 19,
Does not show up window, when clicking on "Search files...".
Bellow, trace. I can't realize things thou... Thanks!

Traceback (most recent call last):
File "/home/careca/.local/share/gedit/plugins/file-search/plugin.py", line 127, in on_search_files_activate
self.openSearchDialog()
File "/home/careca/.local/share/gedit/plugins/file-search/plugin.py", line 131, in _openSearchDialog
self.searchDialog = SearchDialog(self, self.window)
File "/home/careca/.local/share/gedit/plugins/file-search/searchdialog.py", line 154, in init
self.gclient = self.initGSettings()
File "/home/careca/.local/share/gedit/plugins/file-search/search_dialog.py", line 172, in initGSettings
resourceDir, Gio.SettingsSchemaSource.get_default(), False)
File "/usr/lib64/python3.3/site-packages/gi/types.py", line 137, in constructor
return info.invoke(cls, args, *kwargs)
gi._glib.GError: Datei »/home/careca/.local/share/gedit/plugins/file-search/gschemas.compiled« konnte nicht geöffnet werden: open() ist gescheitert: Datei oder Verzeichnis nicht gefunden
- translation of last line:
  "gi._glib.GError: File »/home/careca/.local/share/gedit/plugins/file-search/gschemas.compiled« could not be opened: open () failed: File or directory not found")

**Comment by oliver** [comment]
Can you post the list of files in /home/careca/.local/share/gedit/plugins/, eg. the output from `ls -lR /home/careca/.local/share/gedit/plugins/`?

**Comment by careca1970** [comment]
Hi, thanks for reply!
In fact, the user-name reads "Alex", not "careca". I just came to the idea, that the user-name containing "capitals" MAY NOT BE a good idea. Thou...
...until this date (after some years) I had never seen problems related to my user-name...

Further, back to "gi._glib.GError:...", I can't understand why it should expect to see "gschemas.compiled" under the gedit-plugins path....

Here is the output you asked for:

ls -lR ~/.local/share/gedit/plugins/
/home/Alex/.local/share/gedit/plugins/:
insgesamt 84
drwxrwxr-x. 4 Alex Alex 4096 14. Feb 11:21 file-search
-rw-rw-r--. 1 Alex Alex  616  5. Feb 23:38 file-search-before-gedit38.plugin
-rw-rw-r--. 1 Alex Alex  537  5. Feb 23:38 file-search.plugin
-rw-rw-r--. 1 Alex Alex 1789  5. Feb 23:38 Makefile
-rw-rw-r--. 1 Alex Alex 1975  5. Feb 23:38 notes-de.txt
-rw-rw-r--. 1 Alex Alex 2600  5. Feb 23:38 notes.txt
drwxrwxr-x. 2 Alex Alex 4096 13. Feb 20:06 **pycache**
drwxrwxr-x. 3 Alex Alex 4096 13. Feb 15:32 sessionsaver
-rw-rw-r--. 1 Alex Alex 6224 13. Feb 15:32 sessionsaver.plugin
-rw-rw-r--. 1 Alex Alex  272 28. Okt 22:56 template.plugin
-rw-rw-r--. 1 Alex Alex 4231 28. Okt 22:56 template.py
drwxrwxr-x. 2 Alex Alex 4096  5. Feb 23:38 testfiles
drwxrwxr-x. 4 Alex Alex 4096  7. Feb 21:46 toggletextwrapping
-rw-rw-r--. 1 Alex Alex  534 31. Okt 17:20 toggletextwrapping.plugin
-rw-rw-r--. 1 Alex Alex 2744 31. Okt 17:20 toggletextwrappingREADME.md
-rw-rw-r--. 1 Alex Alex  269 23. Aug 03:34 trailingspaces.plugin
-rw-rw-r--. 1 Alex Alex 4322 23. Aug 03:34 trailingspaces.py
-rw-rw-r--. 1 Alex Alex  168 23. Aug 03:34 trailingspacesREADME.md

/home/Alex/.local/share/gedit/plugins/file-search:
insgesamt 104
-rw-rw-r--. 1 Alex Alex 27665  5. Feb 23:38 file-search.ui
-rw-rw-r--. 1 Alex Alex   935  5. Feb 23:38 **init**.py
-rw-rw-r--. 1 Alex Alex  1005  5. Feb 23:38 io.github.oliver.gedit-file-search.gschema.xml
drwxrwxr-x. 5 Alex Alex  4096  5. Feb 23:38 locale
-rw-rw-r--. 1 Alex Alex  1699  5. Feb 23:38 plugin_common.py
-rw-rw-r--. 1 Alex Alex  9376  5. Feb 23:38 plugin.py
drwxrwxr-x. 2 Alex Alex  4096 13. Feb 23:24 **pycache**
-rw-rw-r--. 1 Alex Alex 14018  5. Feb 23:38 result_panel.py
-rw-rw-r--. 1 Alex Alex 15997  5. Feb 23:38 search_dialog.py
-rw-rw-r--. 1 Alex Alex 10672  5. Feb 23:38 searcher.py

/home/Alex/.local/share/gedit/plugins/file-search/locale:
insgesamt 12
drwxrwxr-x. 3 Alex Alex 4096  5. Feb 23:38 de
drwxrwxr-x. 3 Alex Alex 4096  5. Feb 23:38 fr
drwxrwxr-x. 3 Alex Alex 4096  5. Feb 23:38 ru

/home/Alex/.local/share/gedit/plugins/file-search/locale/de:
insgesamt 4
drwxrwxr-x. 2 Alex Alex 4096  5. Feb 23:38 LC_MESSAGES

/home/Alex/.local/share/gedit/plugins/file-search/locale/de/LC_MESSAGES:
insgesamt 8
-rw-rw-r--. 1 Alex Alex 4434  5. Feb 23:38 file-search.po

/home/Alex/.local/share/gedit/plugins/file-search/locale/fr:
insgesamt 4
drwxrwxr-x. 2 Alex Alex 4096  5. Feb 23:38 LC_MESSAGES

/home/Alex/.local/share/gedit/plugins/file-search/locale/fr/LC_MESSAGES:
insgesamt 8
-rw-rw-r--. 1 Alex Alex 4609  5. Feb 23:38 file-search.po

/home/Alex/.local/share/gedit/plugins/file-search/locale/ru:
insgesamt 4
drwxrwxr-x. 2 Alex Alex 4096  5. Feb 23:38 LC_MESSAGES

/home/Alex/.local/share/gedit/plugins/file-search/locale/ru/LC_MESSAGES:
insgesamt 8
-rw-rw-r--. 1 Alex Alex 5118  5. Feb 23:38 file-search.po

/home/Alex/.local/share/gedit/plugins/file-search/**pycache**:
insgesamt 68
-rw-rw-r--. 1 Alex Alex   247 13. Feb 23:24 **init**.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex  1438 13. Feb 23:24 plugin_common.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex 11429 13. Feb 23:24 plugin.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex 15546 13. Feb 23:24 result_panel.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex 15503 13. Feb 23:24 search_dialog.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex 12559 13. Feb 23:24 searcher.cpython-33.pyc

/home/Alex/.local/share/gedit/plugins/**pycache**:
insgesamt 16
-rw-rw-r--. 1 Alex Alex 6867 13. Feb 20:06 template.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex 5790  7. Feb 20:44 trailingspaces.cpython-33.pyc

/home/Alex/.local/share/gedit/plugins/sessionsaver:
insgesamt 52
-rw-rw-r--. 1 Alex Alex 5553 13. Feb 15:32 dialogs.py
-rw-rw-r--. 1 Alex Alex  120 13. Feb 15:32 gpdefs.py
-rw-rw-r--. 1 Alex Alex 5926 13. Feb 15:32 **init**.py
-rw-rw-r--. 1 Alex Alex  651 13. Feb 15:32 Makefile.am
drwxrwxr-x. 2 Alex Alex 4096 13. Feb 15:32 **pycache**
-rw-rw-r--. 1 Alex Alex  240 13. Feb 15:32 sessionsaver.plugin.desktop.in.in
-rw-rw-r--. 1 Alex Alex 9704 13. Feb 15:32 sessionsaver.ui
-rw-rw-r--. 1 Alex Alex 5372 13. Feb 15:32 store.py

/home/Alex/.local/share/gedit/plugins/sessionsaver/**pycache**:
insgesamt 40
-rw-rw-r--. 1 Alex Alex 10914 13. Feb 15:32 dialogs.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex   266 13. Feb 15:32 gpdefs.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex  8388 13. Feb 15:32 **init**.cpython-33.pyc
-rw-rw-r--. 1 Alex Alex 10085 13. Feb 15:32 store.cpython-33.pyc

/home/Alex/.local/share/gedit/plugins/testfiles:
insgesamt 140
-rw-rw-r--. 1 Alex Alex     33 13. Feb 23:23 another'test"file
-rw-rw-r--. 1 Alex Alex    205 13. Feb 23:23 evil_binary_file_1.bin
-rw-rw-r--. 1 Alex Alex   1963 13. Feb 23:23 file_for_whole_word_option.txt
-rw-rw-r--. 1 Alex Alex     53 13. Feb 23:23 file with spaces
-rw-rw-r--. 1 Alex Alex    223 13. Feb 23:23 testfile:with_evil_name_1
-rw-rw-r--. 1 Alex Alex 111037 13. Feb 23:23 text_with_binary.txt
-rw-rw-r--. 1 Alex Alex      5 13. Feb 23:23 U+0130_LATIN_CAPITAL_LETTER_I_WITH_DOT_ABOVE.txt
-rw-rw-r--. 1 Alex Alex    750 13. Feb 23:23 utf8-extract-1.bin

/home/Alex/.local/share/gedit/plugins/toggletextwrapping:
insgesamt 16
-rw-rw-r--. 1 Alex Alex 5162 31. Okt 17:20 **init**.py
drwxrwxr-x. 2 Alex Alex 4096  7. Feb 21:46 **pycache**
drwxrwxr-x. 3 Alex Alex 4096  7. Feb 21:46 utils

/home/Alex/.local/share/gedit/plugins/toggletextwrapping/**pycache**:
insgesamt 8
-rw-rw-r--. 1 Alex Alex 7332  7. Feb 21:46 **init**.cpython-33.pyc

/home/Alex/.local/share/gedit/plugins/toggletextwrapping/utils:
insgesamt 52
-rw-rw-r--. 1 Alex Alex    76 31. Okt 17:20 Changelog
-rw-rw-r--. 1 Alex Alex  2037 31. Okt 17:20 **init**.py
-rw-rw-r--. 1 Alex Alex 35147 31. Okt 17:20 LICENSE
drwxrwxr-x. 2 Alex Alex  4096  7. Feb 21:46 **pycache**
-rw-rw-r--. 1 Alex Alex   983 31. Okt 17:20 README.md

/home/Alex/.local/share/gedit/plugins/toggletextwrapping/utils/**pycache**:
insgesamt 4
-rw-rw-r--. 1 Alex Alex 3145  7. Feb 21:46 **init**.cpython-33.pyc

**Comment by oliver** [comment]
Hehe, the "testfiles" directory is a hint: maybe you downloaded the _source code_ (like with "Download ZIP" button at https://github.com/oliver/gedit-file-search)?

Could you try the file from https://github.com/oliver/gedit-file-search/releases/download/GEDIT_FILE_SEARCH_V1.1/gedit-file-search-1.1.tgz instead? It should contain the gschemas.compiled file (and usable translations as well).

**Comment by careca1970** [comment]
As expected. Works fine. Thanks for help!

**Comment by oliver** [comment]
Great to hear that it works. Sorry for the confusion with the downloads buttons - I have no idea how to remove the one on front page or how to make it clearer.
