### ISSUE TITLE
Doesn't work on Fedora 20

### ISSUE THREAD

**Issue by romu70** [oliver/gedit-file-search#17]
Hi, your plugin doens't work on Fedora 20 (gEdit 3.10).

The menu item "Search files" is visible, but nothing happens if I click it.

**Comment by oliver** [comment]
Hi, sorry to hear that! Could you try running gedit from terminal (maybe with `gedit -s` to start a brand new instance); then check if there is any output on terminal when starting gedit or when you click Search Files?

Also, does the context menu in gedit have a "Search files..." menu item, and does that work any better?

I guess you have installed the latest plugin version (1.2) as TGZ (gedit-file-search-1.2.tgz)?

Thanks, Oliver

**Comment by romu70** [comment]
Thanks for amazing quick reply!

I directly cloned the repo. Here is the stack trace when I click on "Search files":

> Traceback (most recent call last):
>   File "/home/username/.local/share/gedit/plugins/file-search/plugin.py", line 141, in on_search_files_activate
>     self._openSearchDialog()
>   File "/home/username/.local/share/gedit/plugins/file-search/plugin.py", line 145, in _openSearchDialog
>     self._searchDialog = SearchDialog(self, self._window)
>   File "/home/username/.local/share/gedit/plugins/file-search/search_dialog.py", line 154, in __init__
>     self.gclient = self.initGSettings()
>   File "/home/username/.local/share/gedit/plugins/file-search/search_dialog.py", line 172, in initGSettings
>     resourceDir, Gio.SettingsSchemaSource.get_default(), False)
> gi._glib.GError: Failed to open file '/home/username/.local/share/gedit/plugins/file-search/gschemas.compiled': open() failed: No such file or directory

**Comment by oliver** [comment]
Oh right, you need to run `make` in the cloned repository first - this will create `gschemas.compiled` file (and the translations as well). I'll add this to the README file!

**Comment by romu70** [comment]
Sorry, should have installed from the tgz. It works well. Thanks for all.
