### ISSUE TITLE
Refresh results button

### ISSUE THREAD

**Issue by Delapouite** [oliver/gedit-file-search#5]
Hi Oliver

Would it be possible to add a refresh button just above the close button in the results panel ?
I find it useful because it avoids having to search for the same query multiple times.

**Comment by oliver** [comment]
Yes, good idea... How about a "Search Again..." button which opens the search dialog again with the same values? That would be one more click for simple refresh but might allow other useful functionality.

**Comment by jpfleury** [comment]
I think a "Search Again..." button would be useful.
