### ISSUE TITLE
Max width for "Results" tabs

### ISSUE THREAD

**Issue by jpfleury** [oliver/gedit-file-search#7]
Keywords searched are used as title for the "Results" tab in the bottom panel. The problem is when I search a long string. The "Results" tab makes my gedit window to exceed screen size. May "Results" tabs have a max width.

**Comment by jpfleury** [comment]
See the following screen-shot:

![gedit-file-search-issue-7](https://cloud.githubusercontent.com/assets/687082/4904914/64ab64aa-644b-11e4-9283-e79c8285161c.png)

**Comment by oliver** [comment]
Thanks for noticing this! The Git master now has a limit of 30 characters for the title; could you give it a try?

**Comment by jpfleury** [comment]
It works very well. Thanks a lot. :-)

**Comment by jpfleury** [comment]
Same problem with right-click menu context. The following patch solves the problem:

https://gist.github.com/998143

**Comment by oliver** [comment]
Patch applied; thanks for catching this!

**Comment by oliver** [comment]
This should be fixed with release 0.5.
