### ISSUE TITLE
Find in directory of the currently opened file

### ISSUE THREAD

**Issue by jpfleury** [oliver/gedit-file-search#8]
A lot of time, I use "Ctrl+Shift+F" as I use "Ctrl+F", i.e. with the idea to search in the currently opened file (and other files in the same folder). However, I often must browse to set the folder of the currently opened file (or manually enter it).

I think it would be useful to automatically add directory of the currently opened file in the list of recent searched folders, so it would be easily and quickly selectable.

**Comment by oliver** [comment]
Good idea; maybe the current directory could be added to the bottom of the list (maybe separated by a horizontal line), and probably it should not be saved in Gconf.

**Comment by oliver** [comment]
There's now an initial implementation of this feature on the "lastdir-temps" branch.

**Comment by jpfleury** [comment]
Tested. It works great. :-) It will be very useful.

**Comment by oliver** [comment]
This should be fixed with release 0.6 and 1.0 now - http://olivergerlich.wordpress.com/2013/09/10/gedit-file-search-plugin-1-0-available-now-for-gedit-3/
